services:
  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - private

  back_end:
    depends_on:
      - mongo_db
    build:
      context: ./back-end
    container_name: back_end
    restart: always
    ports:
      - "8000:8000"
    networks:
      - private
      - public
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules

  domain.com:
    depends_on:
      - back_end
    build:
      context: ./front-end/domain.com
    container_name: domain.com
    restart: always
    ports:
      - "5173:5173"
    networks:
      - public
    volumes:
      - ./front-end/domain.com:/usr/src/app
      - /usr/src/app/node_modules

  store.domain.com:
    depends_on:
      - back_end
    build:
      context: ./front-end/store.domain.com
    container_name: store.domain.com
    restart: always
    ports:
      - "5174:5174"
    networks:
      - public
    volumes:
      - ./front-end/store.domain.com:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:

networks:
  private:
  public:
